# CMake generated Testfile for 
# Source directory: /home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples
# Build directory: /home/pengpeng/Ns-3/workspace-test/ns-3-dev/cmake-cache/src/fd-net-device/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dummy-network "ns3.37-dummy-network-debug")
set_tests_properties(ctest-dummy-network PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;3;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd2fd-onoff "ns3.37-fd2fd-onoff-debug")
set_tests_properties(ctest-fd2fd-onoff PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;12;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-realtime-dummy-network "ns3.37-realtime-dummy-network-debug")
set_tests_properties(ctest-realtime-dummy-network PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;21;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-realtime-fd2fd-onoff "ns3.37-realtime-fd2fd-onoff-debug")
set_tests_properties(ctest-realtime-fd2fd-onoff PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;31;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-ping "ns3.37-fd-emu-ping-debug")
set_tests_properties(ctest-fd-emu-ping PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;41;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-udp-echo "ns3.37-fd-emu-udp-echo-debug")
set_tests_properties(ctest-fd-emu-udp-echo PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;50;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-onoff "ns3.37-fd-emu-onoff-debug")
set_tests_properties(ctest-fd-emu-onoff PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;59;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-send "ns3.37-fd-emu-send-debug")
set_tests_properties(ctest-fd-emu-send PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;68;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-tc "ns3.37-fd-emu-tc-debug")
set_tests_properties(ctest-fd-emu-tc PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;79;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-tap-ping "ns3.37-fd-tap-ping-debug")
set_tests_properties(ctest-fd-tap-ping PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;92;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-tap-ping6 "ns3.37-fd-tap-ping6-debug")
set_tests_properties(ctest-fd-tap-ping6 PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;101;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
