# CMake generated Testfile for 
# Source directory: /home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/network/examples
# Build directory: /home/pengpeng/Ns-3/workspace-test/ns-3-dev/cmake-cache/src/network/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bit-serializer "ns3.37-bit-serializer-debug")
set_tests_properties(ctest-bit-serializer PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-header "ns3.37-main-packet-header-debug")
set_tests_properties(ctest-main-packet-header PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-tag "ns3.37-main-packet-tag-debug")
set_tests_properties(ctest-main-packet-tag PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-packet-socket-apps "ns3.37-packet-socket-apps-debug")
set_tests_properties(ctest-packet-socket-apps PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-lollipop-comparisions "ns3.37-lollipop-comparisions-debug")
set_tests_properties(ctest-lollipop-comparisions PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/network/examples/CMakeLists.txt;0;")
