# CMake generated Testfile for 
# Source directory: /home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/internet/examples
# Build directory: /home/pengpeng/Ns-3/workspace-test/ns-3-dev/cmake-cache/src/internet/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-main-simple "ns3.37-main-simple-debug")
set_tests_properties(ctest-main-simple PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/internet/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/internet/examples/CMakeLists.txt;1;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/internet/examples/CMakeLists.txt;0;")
add_test(ctest-neighbor-cache-example "ns3.37-neighbor-cache-example-debug")
set_tests_properties(ctest-neighbor-cache-example PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/internet/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/internet/examples/CMakeLists.txt;10;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/internet/examples/CMakeLists.txt;0;")
add_test(ctest-neighbor-cache-dynamic "ns3.37-neighbor-cache-dynamic-debug")
set_tests_properties(ctest-neighbor-cache-dynamic PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/internet/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/internet/examples/CMakeLists.txt;20;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/internet/examples/CMakeLists.txt;0;")
