# CMake generated Testfile for 
# Source directory: /home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/sixlowpan/examples
# Build directory: /home/pengpeng/Ns-3/workspace-test/ns-3-dev/cmake-cache/src/sixlowpan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-example-sixlowpan "ns3.37-example-sixlowpan-debug")
set_tests_properties(ctest-example-sixlowpan PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;1;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan "ns3.37-example-ping-lr-wpan-debug")
set_tests_properties(ctest-example-ping-lr-wpan PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;12;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-beacon "ns3.37-example-ping-lr-wpan-beacon-debug")
set_tests_properties(ctest-example-ping-lr-wpan-beacon PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;23;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-mesh-under "ns3.37-example-ping-lr-wpan-mesh-under-debug")
set_tests_properties(ctest-example-ping-lr-wpan-mesh-under PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;34;build_lib_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/src/sixlowpan/examples/CMakeLists.txt;0;")
