# CMake generated Testfile for 
# Source directory: /home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial
# Build directory: /home/pengpeng/Ns-3/workspace-test/ns-3-dev/cmake-cache/examples/tutorial
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-hello-simulator "ns3.37-hello-simulator-debug")
set_tests_properties(ctest-hello-simulator PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1618;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;1;build_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-first "ns3.37-first-debug")
set_tests_properties(ctest-first PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1618;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;7;build_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-second "ns3.37-second-debug")
set_tests_properties(ctest-second PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1618;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;17;build_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-third "ns3.37-third-debug")
set_tests_properties(ctest-third PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1618;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;28;build_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-fourth "ns3.37-fourth-debug")
set_tests_properties(ctest-fourth PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1618;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;40;build_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-fifth "ns3.37-fifth-debug")
set_tests_properties(ctest-fifth PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1618;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;46;build_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-sixth "ns3.37-sixth-debug")
set_tests_properties(ctest-sixth PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1618;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;57;build_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-seventh "ns3.37-seventh-debug")
set_tests_properties(ctest-seventh PROPERTIES  WORKING_DIRECTORY "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1411;add_test;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/build-support/macros-and-definitions.cmake;1618;build_exec;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;68;build_example;/home/pengpeng/Ns-3/workspace-test/ns-3-dev/examples/tutorial/CMakeLists.txt;0;")
